# toir.masterdoc.pro — redirect to fixaverse.ru

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name toir.masterdoc.pro;

    ssl_certificate /etc/letsencrypt/live/toir.masterdoc.pro/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toir.masterdoc.pro/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://fixaverse.ru$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name toir.masterdoc.pro;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
        allow all;
    }

    return 301 https://fixaverse.ru$request_uri;
}
